name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  metrics-follow-up:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@v3.32
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          
          plugin_notable: yes
          plugin_notable_filter: stars:>200 forks:>50
          plugin_notable_from: organization
          plugin_notable_repositories: yes
#           plugin_notable_skipped: 
          plugin_notable_indepth: yes
          
          plugin_followup: yes
          plugin_followup_indepth: yes
          
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          plugin_languages_recent_days: 60
          
          user: e1ijah1
  

